### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Counterply** [double-beep/asmFish#32]
Hi @double-beep 

Great job on the wiki. Do you know if there is there a way to easily merge it with the master? A wiki equivalent of a PR would be nice.

**Comment by double-beep** [comment]
I can either send you an e-mail or comment the code of the page you want or you can clone the wiki with the command
```
git clone https://github.com/double-beep/asmFish.wiki.git
```
or  

![wikis](https://help.github.com/assets/images/help/wiki/wiki_clone_url.png)
